# Generated by Django 5.2.7 on 2025-10-14 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('from_email', models.CharField(blank=True, max_length=255)),
                ('to_email', models.CharField(blank=True, max_length=255)),
                ('received_at', models.DateTimeField()),
                ('raw_html', models.TextField(blank=True)),
                ('raw_text', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='ingestion_r_user_id_eb1c97_idx'), models.Index(fields=['message_id'], name='ingestion_r_message_d80f26_idx'), models.Index(fields=['received_at'], name='ingestion_r_receive_be621a_idx')],
            },
        ),
    ]
