# Generated by Django 5.2.7 on 2025-10-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100, unique=True)),
                ('default_return_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['merchant_name'],
                'indexes': [models.Index(fields=['merchant_name'], name='merchants_m_merchan_cd57be_idx')],
            },
        ),
    ]
