# Generated by Django 5.2.7 on 2025-10-22 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_raw_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('product_size', models.CharField(blank=True, max_length=50)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_name', models.CharField(blank=True, max_length=200)),
                ('return_deadline', models.DateField(blank=True, null=True)),
                ('return_status', models.CharField(choices=[('not_returned', 'Not Returned'), ('return_requested', 'Return Requested'), ('returned', 'Returned'), ('return_rejected', 'Return Rejected')], default='not_returned', max_length=20)),
                ('return_requested_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['order'], name='orders_orde_order_i_d30f9b_idx'), models.Index(fields=['return_deadline'], name='orders_orde_return__f9a637_idx'), models.Index(fields=['return_status'], name='orders_orde_return__6d7220_idx')],
            },
        ),
    ]
